# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Sat Dec  6 22:15:54 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(632, 521)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 40, 291, 381))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 201, 129))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 3, 0, 1, 1)
        self.comboBox_1 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_1, 2, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_3, 4, 0, 1, 1)
        self.genTop10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.genTop10.setObjectName(_fromUtf8("genTop10"))
        self.gridLayout.addWidget(self.genTop10, 6, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_4, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 270, 201, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 300, 201, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 390, 201, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 360, 201, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 330, 70, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 330, 70, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 30, 121, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 240, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie lens", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Western", None))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_1.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_1.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_1.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_1.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_1.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_1.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_1.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_1.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_1.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_1.setItemText(18, _translate("MainWindow", "Western", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "Western", None))
        self.genTop10.setText(_translate("MainWindow", "Generate list", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Top 10", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Top 20", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Top 30", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Top 50", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Top 75", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Top 100", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Top 150", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Top 200", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Top 250", None))
        self.label.setText(_translate("MainWindow", "Top list generator", None))
        self.lineEdit.setText(_translate("MainWindow", "Please enter a UserID", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Please write the title or ID of your movie", None))
        self.pushButton.setText(_translate("MainWindow", "Generate rating prediction", None))
        self.pushButton_2.setText(_translate("MainWindow", "Generate random UserID and MovieID", None))
        self.checkBox.setText(_translate("MainWindow", "MovieID", None))
        self.checkBox_2.setText(_translate("MainWindow", "Movie title", None))
        self.label_2.setText(_translate("MainWindow", "Rating prediction", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Sat Dec  6 22:17:14 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(632, 521)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 40, 291, 381))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 201, 129))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 3, 0, 1, 1)
        self.comboBox_1 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_1.setObjectName(_fromUtf8("comboBox_1"))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.comboBox_1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_1, 2, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_3, 4, 0, 1, 1)
        self.genTop10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.genTop10.setObjectName(_fromUtf8("genTop10"))
        self.gridLayout.addWidget(self.genTop10, 6, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_4, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 270, 201, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 300, 201, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 390, 201, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 360, 201, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 330, 70, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(110, 330, 70, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 30, 121, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 240, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie lens", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Western", None))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_1.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_1.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_1.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_1.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_1.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_1.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_1.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_1.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_1.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_1.setItemText(18, _translate("MainWindow", "Western", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Action", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Animation", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Crime", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Drama", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Horror", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Musical", None))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "Romance", None))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "War", None))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "Western", None))
        self.genTop10.setText(_translate("MainWindow", "Generate list", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Top 10", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Top 20", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Top 30", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Top 50", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Top 75", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Top 100", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Top 150", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Top 200", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Top 250", None))
        self.label.setText(_translate("MainWindow", "Top list generator", None))
        self.lineEdit.setText(_translate("MainWindow", "Please enter a UserID", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Please write the title or ID of your movie", None))
        self.pushButton.setText(_translate("MainWindow", "Generate rating prediction", None))
        self.pushButton_2.setText(_translate("MainWindow", "Generate random UserID and MovieID", None))
        self.checkBox.setText(_translate("MainWindow", "MovieID", None))
        self.checkBox_2.setText(_translate("MainWindow", "Movie title", None))
        self.label_2.setText(_translate("MainWindow", "Rating prediction", None))

