# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Sun Dec  7 11:27:01 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(638, 477)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 40, 291, 381))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 70, 201, 129))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Genre_2_dropdown = QtGui.QComboBox(self.gridLayoutWidget)
        self.Genre_2_dropdown.setObjectName(_fromUtf8("Genre_2_dropdown"))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.Genre_2_dropdown.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Genre_2_dropdown, 3, 0, 1, 1)
        self.Genre_1_dropdown = QtGui.QComboBox(self.gridLayoutWidget)
        self.Genre_1_dropdown.setObjectName(_fromUtf8("Genre_1_dropdown"))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.Genre_1_dropdown.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Genre_1_dropdown, 2, 0, 1, 1)
        self.Genre_3_dropdown = QtGui.QComboBox(self.gridLayoutWidget)
        self.Genre_3_dropdown.setObjectName(_fromUtf8("Genre_3_dropdown"))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.Genre_3_dropdown.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Genre_3_dropdown, 4, 0, 1, 1)
        self.genTop10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.genTop10.setObjectName(_fromUtf8("genTop10"))
        self.gridLayout.addWidget(self.genTop10, 6, 0, 1, 1)
        self.Top_x_dropdown = QtGui.QComboBox(self.gridLayoutWidget)
        self.Top_x_dropdown.setObjectName(_fromUtf8("Top_x_dropdown"))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.Top_x_dropdown.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Top_x_dropdown, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.User_Line = QtGui.QLineEdit(self.centralwidget)
        self.User_Line.setGeometry(QtCore.QRect(40, 270, 201, 20))
        self.User_Line.setObjectName(_fromUtf8("User_Line"))
        self.Movie_line = QtGui.QLineEdit(self.centralwidget)
        self.Movie_line.setGeometry(QtCore.QRect(40, 300, 201, 20))
        self.Movie_line.setObjectName(_fromUtf8("Movie_line"))
        self.Gen_rating_btn = QtGui.QPushButton(self.centralwidget)
        self.Gen_rating_btn.setGeometry(QtCore.QRect(40, 390, 201, 23))
        self.Gen_rating_btn.setObjectName(_fromUtf8("Gen_rating_btn"))
        self.Gen_ran_btn = QtGui.QPushButton(self.centralwidget)
        self.Gen_ran_btn.setGeometry(QtCore.QRect(40, 360, 201, 23))
        self.Gen_ran_btn.setObjectName(_fromUtf8("Gen_ran_btn"))
        self.MovieID_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.MovieID_checkbox.setGeometry(QtCore.QRect(40, 330, 70, 17))
        self.MovieID_checkbox.setChecked(True)
        self.MovieID_checkbox.setAutoExclusive(False)
        self.MovieID_checkbox.setObjectName(_fromUtf8("MovieID_checkbox"))
        self.MovieTitle_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.MovieTitle_checkbox.setGeometry(QtCore.QRect(120, 330, 70, 17))
        self.MovieTitle_checkbox.setObjectName(_fromUtf8("MovieTitle_checkbox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 30, 121, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 240, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.MovieID_checkbox, QtCore.SIGNAL(_fromUtf8("clicked()")), self.MovieTitle_checkbox.toggle)
        QtCore.QObject.connect(self.MovieTitle_checkbox, QtCore.SIGNAL(_fromUtf8("clicked()")), self.MovieID_checkbox.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie lens", None))
        self.Genre_2_dropdown.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.Genre_2_dropdown.setItemText(1, _translate("MainWindow", "Action", None))
        self.Genre_2_dropdown.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.Genre_2_dropdown.setItemText(3, _translate("MainWindow", "Animation", None))
        self.Genre_2_dropdown.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.Genre_2_dropdown.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.Genre_2_dropdown.setItemText(6, _translate("MainWindow", "Crime", None))
        self.Genre_2_dropdown.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.Genre_2_dropdown.setItemText(8, _translate("MainWindow", "Drama", None))
        self.Genre_2_dropdown.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.Genre_2_dropdown.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.Genre_2_dropdown.setItemText(11, _translate("MainWindow", "Horror", None))
        self.Genre_2_dropdown.setItemText(12, _translate("MainWindow", "Musical", None))
        self.Genre_2_dropdown.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.Genre_2_dropdown.setItemText(14, _translate("MainWindow", "Romance", None))
        self.Genre_2_dropdown.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.Genre_2_dropdown.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.Genre_2_dropdown.setItemText(17, _translate("MainWindow", "War", None))
        self.Genre_2_dropdown.setItemText(18, _translate("MainWindow", "Western", None))
        self.Genre_1_dropdown.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.Genre_1_dropdown.setItemText(1, _translate("MainWindow", "Action", None))
        self.Genre_1_dropdown.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.Genre_1_dropdown.setItemText(3, _translate("MainWindow", "Animation", None))
        self.Genre_1_dropdown.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.Genre_1_dropdown.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.Genre_1_dropdown.setItemText(6, _translate("MainWindow", "Crime", None))
        self.Genre_1_dropdown.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.Genre_1_dropdown.setItemText(8, _translate("MainWindow", "Drama", None))
        self.Genre_1_dropdown.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.Genre_1_dropdown.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.Genre_1_dropdown.setItemText(11, _translate("MainWindow", "Horror", None))
        self.Genre_1_dropdown.setItemText(12, _translate("MainWindow", "Musical", None))
        self.Genre_1_dropdown.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.Genre_1_dropdown.setItemText(14, _translate("MainWindow", "Romance", None))
        self.Genre_1_dropdown.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.Genre_1_dropdown.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.Genre_1_dropdown.setItemText(17, _translate("MainWindow", "War", None))
        self.Genre_1_dropdown.setItemText(18, _translate("MainWindow", "Western", None))
        self.Genre_3_dropdown.setItemText(0, _translate("MainWindow", "Pick a genre", None))
        self.Genre_3_dropdown.setItemText(1, _translate("MainWindow", "Action", None))
        self.Genre_3_dropdown.setItemText(2, _translate("MainWindow", "Adventure", None))
        self.Genre_3_dropdown.setItemText(3, _translate("MainWindow", "Animation", None))
        self.Genre_3_dropdown.setItemText(4, _translate("MainWindow", "Children\'s", None))
        self.Genre_3_dropdown.setItemText(5, _translate("MainWindow", "Comedy", None))
        self.Genre_3_dropdown.setItemText(6, _translate("MainWindow", "Crime", None))
        self.Genre_3_dropdown.setItemText(7, _translate("MainWindow", "Documentary", None))
        self.Genre_3_dropdown.setItemText(8, _translate("MainWindow", "Drama", None))
        self.Genre_3_dropdown.setItemText(9, _translate("MainWindow", "Fantasy", None))
        self.Genre_3_dropdown.setItemText(10, _translate("MainWindow", "Film-Noir", None))
        self.Genre_3_dropdown.setItemText(11, _translate("MainWindow", "Horror", None))
        self.Genre_3_dropdown.setItemText(12, _translate("MainWindow", "Musical", None))
        self.Genre_3_dropdown.setItemText(13, _translate("MainWindow", "Mystery", None))
        self.Genre_3_dropdown.setItemText(14, _translate("MainWindow", "Romance", None))
        self.Genre_3_dropdown.setItemText(15, _translate("MainWindow", "Sci-fi", None))
        self.Genre_3_dropdown.setItemText(16, _translate("MainWindow", "Thriller", None))
        self.Genre_3_dropdown.setItemText(17, _translate("MainWindow", "War", None))
        self.Genre_3_dropdown.setItemText(18, _translate("MainWindow", "Western", None))
        self.genTop10.setText(_translate("MainWindow", "Generate list", None))
        self.Top_x_dropdown.setItemText(0, _translate("MainWindow", "Top 10", None))
        self.Top_x_dropdown.setItemText(1, _translate("MainWindow", "Top 20", None))
        self.Top_x_dropdown.setItemText(2, _translate("MainWindow", "Top 30", None))
        self.Top_x_dropdown.setItemText(3, _translate("MainWindow", "Top 50", None))
        self.Top_x_dropdown.setItemText(4, _translate("MainWindow", "Top 75", None))
        self.Top_x_dropdown.setItemText(5, _translate("MainWindow", "Top 100", None))
        self.Top_x_dropdown.setItemText(6, _translate("MainWindow", "Top 150", None))
        self.Top_x_dropdown.setItemText(7, _translate("MainWindow", "Top 200", None))
        self.Top_x_dropdown.setItemText(8, _translate("MainWindow", "Top 250", None))
        self.label.setText(_translate("MainWindow", "Top list generator", None))
        self.User_Line.setText(_translate("MainWindow", "Please enter a UserID", None))
        self.Movie_line.setText(_translate("MainWindow", "Please write the title or ID of your movie", None))
        self.Gen_rating_btn.setText(_translate("MainWindow", "Generate rating prediction", None))
        self.Gen_ran_btn.setText(_translate("MainWindow", "Generate random UserID and MovieID", None))
        self.MovieID_checkbox.setText(_translate("MainWindow", "MovieID", None))
        self.MovieTitle_checkbox.setText(_translate("MainWindow", "Movie title", None))
        self.label_2.setText(_translate("MainWindow", "Rating prediction", None))

